version: '3.6'
services:
    client:
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - 8000:8000
        command: sleep 9999
        links:
            - syslog
        logging:
            driver: syslog
            options:
                syslog-address: "udp://127.0.0.1:5514"
                tag: "web"

    message_queue:
        image: rabbitmq:3.7-management
        ports:
            - 15672:15672
            - 5672:5672
        links:
            - syslog
        logging:
            driver: syslog
            options:
                syslog-address: "udp://127.0.0.1:5514"
                tag: "message_queue"

    syslog:
        image: voxxit/rsyslog
        volumes:
          - ../syslog/:/var/log/
        entrypoint: bash -c "rm -f /var/run/rsyslogd.pid && rsyslogd -n"
        ports:
            - "127.0.0.1:5514:514/udp"
